### PR TITLE
added drum kit project

### PR DESCRIPTION
**Pull request by Mohit-Aasirwal**
This is a simple javascript project made with DOM manipulation in javascript.
Kindly merge this PR with issuing hacktoberfest accepted label
#1

### CODE REVIEW

**Comment by Mridul2820** [comment]
Hi @Mohit-Aasirwal Please Follow the [folder naming ](https://github.com/Mridul2820/awesome-javascript#project-folder-name-guidelines)

**Comment by Mohit-Aasirwal** [comment]
I've done pushing the folder in projects subdirectory.
Kindly merge it now by issuing label hacktoberfest-accepted.

**Comment by Mridul2820** [comment]
Hi @Mohit-Aasirwal  Please Change the folder name to `drum-kit`

**Comment by Mohit-Aasirwal** [comment]
Ok, I've done that too.

**Comment by Mridul2820** [comment]
Thank you for contributing! 🚀

**Pull request merged**
