### PR TITLE
[feat]: added quote generator project

### LINKED ISSUE #11: [feat] : Adding a Random quote generator project
A random quote generator project which should generate inspirational quotes from various great professionals.

### PR DESCRIPTION
**Pull request by SohamRatnaparkhi**
Fixes gh: #11 
Added a random quote generator project. This project generates famous and inspirational quotes of various famous personalities.
This project has been written in Vanilla JS only.

- Some screenshots of the project.

image
image

### CODE REVIEW

**Comment by Mridul2820** [comment]
Please add a different issue for this.

**Comment by SohamRatnaparkhi** [comment]
> Please add a different issue for this.

Okay, linked this PR to a different issue.

**Comment by SohamRatnaparkhi** [comment]
Any updates on this PR?

**Review by Mridul2820 — APPROVED** [review]

**Comment by Mridul2820** [comment]
Thank you for contributing! 🚀

**Pull request merged**
